// Code generated by mockery v2.43.0. DO NOT EDIT.

package categories

import (
	context "context"

	model "github.com/kytruong0712/go-market/product-service/api/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

// GetCategoriesHierarchy provides a mock function with given fields: _a0
func (_m *MockController) GetCategoriesHierarchy(_a0 context.Context) (model.CategoriesHierarchy, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoriesHierarchy")
	}

	var r0 model.CategoriesHierarchy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.CategoriesHierarchy, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.CategoriesHierarchy); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.CategoriesHierarchy)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
